# .github/workflows/build.yml
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake autopoint libtool pkg-config gettext \
            build-essential libjpeg-dev libpng-dev libpoppler-glib-dev \
            libjxl-dev ghostscript libppd-dev libcupsfilters-dev

      - name: Bootstrap
        run: ./autogen.sh

      - name: Configure
        run: ./configure

      - name: Build
        run: make -j$(nproc)

      - name: Test
        run: make check

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            config.log
            test-suite.log

